### ISSUE TITLE
add task tracker

### ISSUE THREAD

**Issue by obar1Merger** [obar1/books#105]
- [x] read from json some tasks 

- [x] json struct

```json
{
 taskid:\d
 text:"text"
 time:\dL
}
```

- [x] show timer and mark when done rebuilding the file list

**Comment by obar1** [comment]
I think I do as file based - simpler and we can change to db at some point ;)

**Comment by obar1Merger** [comment]
- [ ] add a simple picker given the json in a dir so I know what to ;)
